[package]
name = "rust-wasm-inference"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["cdylib", "rlib"]
[[bin]]
name = "iris_model_metadata"
path = "src/main.rs"

[dependencies]
ndarray = "0.15"
onnxruntime = "0.0.14"

